# Dockerfile.frontend

# Stage 1: Build the frontend
FROM node:16

WORKDIR /frontend_portfolio

# Copy the package.json and yarn.lock files
COPY frontend_portfolio/package.json frontend_portfolio/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the frontend source files
COPY frontend_portfolio/ ./

# Build the frontend
RUN yarn build

# Keep the container running to allow file copying
CMD ["tail", "-f", "/dev/null"]