version: '3.8'
services:
  backend:
    build:
      context: ./backend_portfolio
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - webnet
    volumes:
      - ./backend_portfolio/app:/app/app
      - /app/venv

  frontend:
    build:
      context: ./frontend_portfolio
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge