version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
