# Dockerfile.backend

# Use an official Python runtime as a parent image for the backend
FROM python:3.9-slim

WORKDIR /app

# Install backend dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend files
COPY app ./app

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the uvicorn server for the FastAPI app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
